spring.application.name=auth-service
server.port=8081

# Logging Configuration
logging.level.root=INFO
logging.level.com.capg.smartcourier=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.file.name=logs/auth-service.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
