services:

  # 🔹 MySQL (Auto create multiple DBs)
  mysql:
    image: mariadb:10.11
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # 🔹 Eureka Server
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mysql

  # 🔹 API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server

  # 🔹 Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  # 🔹 Delivery Service
  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/delivery_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  # 🔹 Tracking Service
  tracking-service:
    build: ./tracking-service
    container_name: tracking-service
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tracking_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  # 🔹 Admin Service
  admin-service:
    build: ./admin-service
    container_name: admin-service
    depends_on:
      - eureka-server

volumes:
  mysql_data: