sonar.projectKey=smart-courier-system   # REQUIRED (you missed this)
sonar.projectName=Smart Courier System
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.java.binaries=**/target/classes
sonar.java.libraries=**/target/**/*.jar

sonar.exclusions=**/test/**

sonar.host.url=http://localhost:9000
sonar.login=sqa_ccbee61d1ad33bf89d669a73ead026f392a4e67d   # Correct Token Binded