server:
  port: 0

spring:
  application:
    name: tracking-service

  datasource:
    url: jdbc:mysql://mysql:3306/tracking_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/