server:
  port: 8082

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:mysql://mysql:3306/delivery_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    preferIpAddress: false
    hostname: delivery-service
    port: 8082
    nonSecurePort: 8082
    nonSecurePortEnabled: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    url: /v3/api-docs
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans